### ISSUE TITLE
Problems with fast_run.py

### ISSUE THREAD

**Issue by ghost** [lixin4ever/BERT-E2E-ABSA#19]
Hi,

when I try to run the fast_run.py even though I have every requirement already installed, I get the following error: 

  File "main.py", line 11, in <module>
    from transformers import AdamW, WarmupLinearSchedule
ImportError: cannot import name 'WarmupLinearSchedule' from 'transformers' (/Users/doruk/opt/anaconda3/lib/python3.8/site-packages/transformers/__init__.py)

**Comment by lixin4ever** [comment]
There is no "WarmupLinearSchedule" in the most recent version of the transformers and you may need to use "get_linear_schedule_with_warmup". Please check the [documentation ](https://huggingface.co/transformers/main_classes/optimizer_schedules.html?highlight=get_linear_schedule#transformers.get_linear_schedule_with_warmup)for more details
