### ISSUE TITLE
Tags for using using raw data on the trained model

### ISSUE THREAD

**Issue by vivektop** [lixin4ever/BERT-E2E-ABSA#21]
Hi @lixin4ever ,Thank you for this amazing work,I have a query on the preparing the raw data for using on the trained model.
If I want to have tags for this data " Service is good,ambience is bad". How can I get this tag with the sentiment along with sentiment(T-POS,T-NEU or NEG).
Like I'm able to get the normal tags like [ B-ORG] using spacy, but to get the data in this format what is the procedure.
Will be very useful if you can help me on this.

Thanks

**Comment by lixin4ever** [comment]
This feature is mentioned [here](https://github.com/lixin4ever/BERT-E2E-ABSA#quick-start), please check it out. 

You can follow the format of the given data files, for example, [rest16.train](https://github.com/lixin4ever/BERT-E2E-ABSA/blob/master/data/rest16/train.txt), and randomly assign the dummy tags for your input (just to facilitate the input and these tags are not used during inference).

**Comment by vivektop** [comment]
Thank you so much

**Comment by vivektop** [comment]
Hi @lixin4ever , I was trying to run it for unseen data,it is in file named in **data/testinfer.txt.**

But while its trying to read the input file, its not loading at this statement in glue_utils.py.
while trying to open the file using file handler i m getting the error in the below line
**file = os.path.join(data_dir, "%s.txt" % set_type)**

It is taking the path something like this =>No such file or directory: 'data/testinfer.txt\\test.txt'
-------------------
Even if i use file name to open the file, then same kind of path problem is occuring while trying to load the model in work.py
Same path related ERROR : 
FileNotFoundError: [Errno 2] No such file or directory: 'data/testinfer\\cached_test_bert-base-uncased_128_testinfer'

Could you please help on this

Thanks

**Comment by lixin4ever** [comment]
Please read Section [Quick Start](https://github.com/lixin4ever/BERT-E2E-ABSA#quick-start) carefully. In short, you can set the directory name as "testinfer" (in your case) and create a file named "test.txt" for storing the unseen data.

**Comment by vivektop** [comment]
My bad, I misunderstood, Thanks again !
