### ISSUE TITLE
关于self-attention的一个小问题

### ISSUE THREAD

**Issue by xuanzebi** [lixin4ever/BERT-E2E-ABSA#3]
![image](https://user-images.githubusercontent.com/26642184/71168992-e58cc900-2292-11ea-8ab8-41af0129b49c.png)
您好 博主 想问一个问题

如图中的红框部分,,
src = src + self.dropout(src2)
这一部分是是要将原始token的embedding加上过完attention的吗 
不能直接拿attention的输出src2来用作输出吗
加起来是更合理吗？

**Comment by lixin4ever** [comment]
这里是follow transformer的设置，把ffn给去掉，只保留self-attention和residual connection (也就是"src = src + self.dropout(src2)"这行)，
你也可以直接把src2作为SAN的输出(相当于标准的self-attention)，然后看看对结果有没有影响

**Comment by xuanzebi** [comment]
好的 get 谢谢 看来还是要实验证明一下结果了。
其实我个人觉得论文中的TFM
![image](https://user-images.githubusercontent.com/26642184/71172174-85018a00-229a-11ea-8767-a2633e75e61a.png)
这就相当于BERT从12层变成13层了吧.
感觉不是很有必要吧..如果哪里理解不对 请谅解..

**Comment by lixin4ever** [comment]
BERT里的12层TFM是pre-trained的  最后stack上的那一层TFM是随机初始化的 完全靠supervised fine-tuning去学。

我们这里只是测试一下单层的TFM作为下游任务模型时效果如何

**Comment by xuanzebi** [comment]
好的 谢谢~
