### ISSUE TITLE
Question about the situation when `absa_type==crf`

### ISSUE THREAD

**Issue by yangdechuan** [lixin4ever/BERT-E2E-ABSA#4]
https://github.com/lixin4ever/BERT-E2E-ABSA/blob/cf4ddc611f565230744f1b68e429d5f6a92c1ddd/absa_layer.py#L442

I wonder to know why you tranform `tagger_input` into self.classifier when  `absa_type==crf`? That is, you don't use `self.tagger=CRF()` when "absa_type==crf".

**Comment by lixin4ever** [comment]
Thank you for your attention.

Here, we use a simple linear layer to produce emission probability matrix of shape (seq_len, num_labels), which is then fed to CRF layer to calculate the sequence-level log-likelihood (see Line 476).

**Comment by yangdechuan** [comment]
OK, Thanks!
