### ISSUE TITLE
Meaning of a parameter

### ISSUE THREAD

**Issue by Humanpaladin** [lixin4ever/BERT-E2E-ABSA#42]
Hi @lixin4ever

我想请问你下面这个图的参数 |Y| 代表什么啊，是指所有可能 tag 的个数吗？![微信图片_20220717201900](https://user-images.githubusercontent.com/32996197/179397958-d4ede28b-dc48-47a3-928a-02862c01d35a.png)

祝好

**Comment by lixin4ever** [comment]
是的

**Comment by Humanpaladin** [comment]
Many thanks
