### ISSUE TITLE
关于情感一致性和词边界的问题

### ISSUE THREAD

**Issue by KaitoHH** [lixin4ever/BERT-E2E-ABSA#8]
您好，我看到在之前的一篇A Unified Model for Opinion Target Extraction and Target Sentiment Prediction中，您通过Target Boundary Guided TBSA和Maintaining Sentiment Consistency去指导模型避免输出不一致的情感标签或者BIO标签。但是在这篇BERT+不同下游模型的组合中，似乎没有看到使用类似的机制。

请问这些机制在BERT后的下游模型中是不需要考虑的吗？是否基本不会出现类似情感一致性的问题呢？

**Comment by lixin4ever** [comment]
我还没来得及在BERT上验证过这两个component的作用呢，这篇workshop paper只是想要展示下一些基本网络跟BERT结合之后在这个任务上的效果

个人观点：contextualized embedding加上fully connected self-attention对于建模token representation来说已经足够强了，再加上target boundary和sentiment consistency的提升应该不大

**Comment by KaitoHH** [comment]
Many thanks for your intuition!
